export const Products = [
    {
      idProducto: "001",
      nombre: "Dr. Strange",
      description: "Mister of mystic arts",
      foto: "001",
      precio: "5",
      estatus: "active",
      archivo: "001",
      categoria: "Marvel",
    },
    {
        idProducto: "002",
        nombre: "MarkSman",
        description: "Suicide Squad member",
        foto: "002",
        precio: "5",
        estatus: "active",
        archivo: "002",
        categoria: "DC",
      },
      {
        idProducto: "003",
        nombre: "Katana",
        description: "Suicide Squad member",
        foto: "003",
        precio: "5",
        estatus: "active",
        archivo: "003",
        categoria: "DC",
      },
      {
        idProducto: "004",
        nombre: "Metal Gear Rex",
        description: "Nuclear Armed Bipedal Tank PopFold Metal Gear Series",
        foto: "004",
        precio: "10",
        estatus: "active",
        archivo: "004",
        categoria: "Metal Gear",
      },
      {
        idProducto: "005",
        nombre: "Vault Boy",
        description: "Vault-Tec Mascot",
        foto: "005",
        precio: "5",
        estatus: "active",
        archivo: "005",
        categoria: "Games",
      },
      {
        idProducto: "006",
        nombre: "Saitama",
        description: "The Caped Bald",
        foto: "006",
        precio: "5",
        estatus: "active",
        archivo: "006",
        categoria: "Anime",
      },
  ];
  